[package]
name = "Mascal"
version = "0.1.0"
edition = "2024"
authors = ["McBrincie212"]
license = "MIT"
categories = ["parsing", "compilers", "parser-implementations"]

[dependencies]
regex = "1.11.1"
once_cell = "1.18"
num-traits = "0.2.19"
rand = "0.9.1"